import './globals.css'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'JoeAPP',
  description: 'Generated by create next app',
}

// Anything we have that is on everypage, can be put in the layout file

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
        </body>
    </html>
  )
}


// This layout applies to ALL of the pages
// We create a nested layout for auth and dashboard seperatley