import './globals.css'
import { Rubik } from 'next/font/google'

//Components
import Navbar from './ components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Anything we have that is on everypage, can be put in the layout file

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  )
}
